import { BeachIcon } from '../components/BeachIcon'
import { Button } from '../components/ui/button'
import { Card, CardContent } from '../components/ui/card'

const menu = [{ icon: 'heart' as const, label: 'Favoritos' }, { icon: 'card' as const, label: 'Formas de pagamento' }, { icon: 'help' as const, label: 'Ajuda' }]

export function ProfileScreen() {
  return <div className="flex min-h-0 flex-1 flex-col overflow-hidden"><header className="flex shrink-0 items-start justify-between bg-[#0e7a83] px-5 pb-[22px] pt-[18px] text-white"><div><div className="font-['Baloo_2'] text-[19px] font-semibold">Meu perfil</div></div></header><main className="min-h-0 flex-1 overflow-y-auto px-5 pb-[90px] pt-[18px] [scrollbar-width:none]"><div className="mb-[18px] flex items-center gap-3.5"><div className="grid size-[54px] place-items-center rounded-full bg-[#0e7a83] font-['Baloo_2'] text-[17px] font-semibold text-white">MC</div><div><div className="text-[15px] font-bold text-[#173438]">Marina Costa</div><div className="mt-0.5 text-[11.5px] text-[#4c6669]">Cliente desde 2026</div></div></div><Card className="mb-[18px] rounded-[14px] border-0 bg-white py-0 shadow-[0_4px_14px_rgba(23,52,56,0.06)]"><CardContent className="flex p-0 py-3.5">{[['12', 'Pedidos'], ['4', 'Favoritos'], ['4.9', 'Sua nota']].map(([value, label], index) => <div className={`flex flex-1 flex-col items-center gap-0.5 text-center ${index < 2 ? 'border-r border-[#f2dfb8]' : ''}`} key={label}><span className="font-['Baloo_2'] text-[17px] font-semibold text-[#0e7a83]">{value}</span><span className="text-[10.5px] text-[#4c6669]">{label}</span></div>)}</CardContent></Card><Card className="overflow-hidden rounded-[14px] border-0 bg-white py-0 shadow-[0_4px_14px_rgba(23,52,56,0.06)]">{menu.map((item) => <Button variant="ghost" className="h-auto w-full justify-between rounded-none border-b border-[#fbefda] px-4 py-3.5 text-left text-[13px] text-[#173438]" key={item.label}><span className="flex items-center gap-2.5"><BeachIcon name={item.icon} size={17} />{item.label}</span><BeachIcon name="arrow" size={18} /></Button>)}<Button variant="ghost" className="h-auto w-full justify-start rounded-none px-4 py-3.5 text-left text-[13px] text-[#ff6f52]"><span className="flex items-center gap-2.5"><BeachIcon name="logout" size={17} />Sair</span></Button></Card></main></div>
}
